version: '3.0'


services:
  webserver:
    contanier_name:firstproject-web
    build: 
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - .:/app
      -./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      -8080:80



  app:
    contanier_name: Dockerfile.app
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app
